Insert Into tb_province(name_) Values ('北京市')
Insert Into tb_province(name_) Values ('天津市');
Insert Into tb_province(name_) Values ('河北省');
Insert Into tb_province(name_) Values ('山西省');
Insert Into tb_province(name_) Values ('内蒙古');
Insert Into tb_province(name_) Values ('辽宁省');
Insert Into tb_province(name_) Values ('吉林省');
Insert Into tb_province(name_) Values ('黑龙江');
Insert Into tb_province(name_) Values ('上海市');
Insert Into tb_province(name_) Values ('江苏省');
Insert Into tb_province(name_) Values ('浙江省');
Insert Into tb_province(name_) Values ('安徽省');
Insert Into tb_province(name_) Values ('福建省');
Insert Into tb_province(name_) Values ('江西省');
Insert Into tb_province(name_) Values ('山东省');
Insert Into tb_province(name_) Values ('河南省');
Insert Into tb_province(name_) Values ('湖北省');
Insert Into tb_province(name_) Values ('湖南省');
Insert Into tb_province(name_) Values ('广东省');
Insert Into tb_province(name_) Values ('广  西');
Insert Into tb_province(name_) Values ('海南省');
Insert Into tb_province(name_) Values ('重庆市');
Insert Into tb_province(name_) Values ('四川省');
Insert Into tb_province(name_) Values ('贵州省');
Insert Into tb_province(name_) Values ('云南省');
Insert Into tb_province(name_) Values ('西  藏');
Insert Into tb_province(name_) Values ('陕西省');
Insert Into tb_province(name_) Values ('甘肃省');
Insert Into tb_province(name_) Values ('青海省');
Insert Into tb_province(name_) Values ('宁  夏');
Insert Into tb_province(name_) Values ('新  疆');
Insert Into tb_province(name_) Values ('台湾省');
Insert Into tb_province(name_) Values ('香  港');
Insert Into tb_province(name_) Values ('澳  门');